openapi: 3.0.3
info:
  title: OpenAPI schema for template terraform-alicloud-kvstore-redis
components:
  schemas:
    variables:
      type: object
      required:
      - infrastructure
      properties:
        context:
          title: Context
          type: object
          description: |
            Receive contextual information. When Walrus deploys, Walrus will inject specific contextual information into this field.
          default: {}
          nullable: true
          additionalProperties:
            type: object
            x-walrus-ui:
              colSpan: 12
          x-walrus-ui:
            colSpan: 12
            group: Advanced
            hidden: true
            order: 1
        infrastructure:
          title: Infrastructure
          type: object
          description: |
            Specify the infrastructure information for deploying.
          required:
          - vpc_id
          properties:
            domain_suffix:
              description: |
                Specify the domain suffix of the PrivateZone. The domain suffix must be a valid DNS name.
              nullable: true
              title: Domain Suffix
              type: string
              x-walrus-ui:
                order: 2
            publicly_accessible:
              default: false
              description: |
                Specify whether to enable public access. If enabled, the Redis service can be accessed from the public network.
              nullable: true
              title: Publicly Accessible
              type: boolean
              x-walrus-ui:
                order: 3
            vpc_id:
              description: |
                Specify the ID of the VPC where the Redis service applies.
              title: Vpc Id
              type: string
              x-walrus-ui:
                order: 1
          x-walrus-ui:
            colSpan: 12
            group: Advanced
            order: 2
        architecture:
          title: Architecture
          type: string
          description: |
            Specify the deployment architecture, select from standalone or replication.
          default: standalone
          enum:
          - standalone
          - replication
          nullable: true
          x-walrus-ui:
            group: Basic
            order: 3
        replication_readonly_replicas:
          title: Replication Readonly Replicas
          type: number
          description: |
            Specify the number of read-only replicas under the replication deployment.
          default: 1
          enum:
          - 1
          - 3
          - 5
          nullable: true
          x-walrus-ui:
            group: Basic
            order: 4
            showIf: architecture=replication
        engine_version:
          title: Engine Version
          type: string
          description: |
            Specify the deployment engine version.
          default: "5.0"
          enum:
          - "5.0"
          - "4.0"
          nullable: true
          x-walrus-ui:
            group: Basic
            order: 5
        password:
          title: Password
          type: string
          description: |
            Specify the account password. The password must be 16-32 characters long and start with any letter, number, or the following symbols: ! # $ % ^ & * ( ) _ + - =.
            If not specified, it will generate a random password.
          format: password
          nullable: true
          writeOnly: true
          minLength: 16
          maxLength: 32
          x-walrus-ui:
            group: Basic
            order: 7
      x-walrus-ui:
        groupOrder:
        - Basic
        - Advanced
